services:
  - type: web
    name: reckonix-crm
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: SESSION_SECRET
        generateValue: true
      - key: USE_MONGODB
        value: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_PASSWORD
        sync: false
